### ISSUE TITLE
Introduce `SubFrames` as extended `Group` and covering `window` feature

### ISSUE THREAD

**Issue by heronshoes** [heronshoes/red_amber#170]
I am considering about the new class `Party` which will cover existing `Group` and incoming `window` feature. This is an experimental feature and may be slow so `Group` class will remain as it is.

 ==> I will use `SubFrames` instead of `Party`.

Concept card in English(deprecated):
[concept_party_en](https://user-images.githubusercontent.com/63298319/213361646-b8542aaa-f3ac-41d5-81bb-b4e63c9be775.png)

Concept card in Japanese(deprecated):
[concept_party_jp](https://user-images.githubusercontent.com/63298319/213360779-2608ac28-0e72-4345-a7ad-3a55733a3cd6.png)

**Comment by heronshoes** [comment]
I think `Party` may not be a good name. Members of a `Party` are dataframes. The concept includes non MECE subsets.
- dataframe.group # => a instance of Group, for compatibility
- dataframe.part(type: :group) # => a instance of Party by grouping by valus
- dataframe.window(size: nil) # => a instance of Party by windowing (New feature)
- dataframe.part(type: :window, step: nil, kernel: nil)
  # => a instance of Party by windowing
- dataframe.part { custom_grouping_or_windowing_rule } # => a instance of Party

`Party` will be `SubFrames`.
- dataframe.group # => a instance of Group, for compatibility
- dataframe.to_subsets(type: :group) # => a instance of Subsets by grouping by valus
- dataframe.window(size: nil) # => a instance of Subsets by windowing (New feature)
- dataframe.to_subsets(type: :window, step: nil, kernel: nil)
  # => a instance of Subsets by windowing
- dataframe.part { custom_grouping_or_windowing_rule } # => a instance of Subsets

**Comment by heronshoes** [comment]
To create SubFrames from two different dataframes;

```ruby
[dataframe1, dataframe2].to_subframes # => a instance of SubFrames
```

**Comment by dsisnero** [comment]
supergroup , collection as possible alternatives for party

**Comment by heronshoes** [comment]
Thanks @dsisnero !
It is good to show that SuperGroup is upper compatible with Group, but it may not be well shown that it is a concept that includes Window.
Collection is also a good name, but I am not sure how it differs from Array of DataFrames.
So far, SubFrames seems the most comfortable to me, since it shows that it is subsets of DataFrame, which is the most important point of abstraction.

**Comment by heronshoes** [comment]
![SubFrames_en](https://user-images.githubusercontent.com/63298319/213947784-4c78df5b-3877-42a5-97d7-267e73f9a931.png)

![SubFrames_jp](https://user-images.githubusercontent.com/63298319/213947810-483314e2-acc1-4cc9-be9d-453e47c3fde3.png)
