### ISSUE TITLE
Support for Jupyter Notebook?

### ISSUE THREAD

**Issue by kojix2** [heronshoes/red_amber#29]
Hi! @heronshoes 

I was trying RedAmber in [Jupyter](https://jupyter.org/) + [IRuby](https://github.com/SciRuby/iruby).

![image](https://user-images.githubusercontent.com/5798442/173548340-89ce67c6-98b8-429b-86e1-6770f471d41e.png)
I found that Juypter does not display data frames in a tabular format.

Rover :
![image](https://user-images.githubusercontent.com/5798442/173549790-a9542850-dbed-4cf1-ac84-c2b4bb410359.png)

Pandas :
![image](https://user-images.githubusercontent.com/5798442/173548657-3cf9cc78-3ddf-4bfb-aebc-3ca4aa30cb30.png)

This feature is **not** needed immediately, but I hope you will consider providing it when you have time.

Thank you.

**Comment by heronshoes** [comment]
Thank you for using RedAmber :+1:

I will try to introduce `to_html` method with iruby.

**Comment by kojix2** [comment]
Thank you very much. It worked.
![image](https://user-images.githubusercontent.com/5798442/173726763-f8fafda4-d28c-4838-8e6f-36b325a4596b.png)

**Comment by heronshoes** [comment]
## Reuse issue to add feature :recycle:

`nil` is not visible in Jupyter.

Can you see the ghost?
![jupyterlab](https://user-images.githubusercontent.com/63298319/174219841-917d78c2-9531-4e3d-8dcf-39fc1810fd23.png)

`nil`, `''`, `\s+` are not visible in Jupyter (by `DataFrame#to_iruby`).

Proposals are;
- nil is expressed as <i>(nil)</i>
- empty string('') is <i>""</i>
- blank spaces are <i>" "</i>

**Comment by kojix2** [comment]
mrkn is the owner of IRuby, and I have commit rights. If you encounter a case where you want to change IRuby in implementing red-amber, please report it to IRuby. There is a good chance that your change proposal will be approved.

**Comment by heronshoes** [comment]
Thanks @kojix2 !
Fortunately this is a data preparation issue in RedAmber's side. I can implement as #32 .
