### ISSUE TITLE
`arrow-devel` not available for Fedora?

### ISSUE THREAD

**Issue by Ashvith** [heronshoes/red_amber#41]
It looks like `arrow-devel` is not available for Fedora. Is there any other alternative to building?

**Comment by heronshoes** [comment]
Hi @Ashvith , I'm sorry I have no idea about it.
I will ask in [Red data tools gitter](https://gitter.im/red-data-tools/en) .

**Comment by kou** [comment]
`libarrow-glib-devel` https://packages.fedoraproject.org/pkgs/libarrow/libarrow-glib-devel/ exists on Fedora Rawhide. Fedora 37 will ship it.

**Comment by kou** [comment]
Red Arrow 9.0.0 will install `libarrow-glib-devel` automatically: https://github.com/apache/arrow/pull/13524
